FROM postgres:17

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Копируем SQL-скрипт для инициализации базы данных
COPY init-scripts/ /docker-entrypoint-initdb.d/

# Делаем файлы исполняемыми (на всякий случай, если есть shell-скрипты)
RUN chmod -R +x /docker-entrypoint-initdb.d/

CMD ["docker-entrypoint-initdb.d"]