
services:
  nginx:
    image: nginx:stable-alpine
    container_name: webgocalc_nginx
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro' # конфигурация nginx
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:17
    container_name: webgocalc_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-stage-runner
    container_name: webgocalc_test
    environment:
      ENV: ${ENV}
      STORAGE_HOST: webgocalc_postgres
      STORAGE_PORT: ${DB_PORT}
      STORAGE_USER: ${DB_USER}
      STORAGE_PASSWORD: ${DB_PASSWORD}
      STORAGE_DBNAME: ${DB_NAME}
      HTTP_SERVER_ADDRESS: ${HTTP_SERVER_ADDRESS}
      HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
      HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
    depends_on:
     - nginx
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: webgocalc_app
    environment:
      ENV: ${ENV}
      STORAGE_HOST: webgocalc_postgres
      STORAGE_PORT: ${DB_PORT}
      STORAGE_USER: ${DB_USER}
      STORAGE_PASSWORD: ${DB_PASSWORD}
      STORAGE_DBNAME: ${DB_NAME}
      HTTP_SERVER_ADDRESS: ${HTTP_SERVER_ADDRESS}
      HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
      HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge