services:
 

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres   # Указание нестандартного имени Dockerfile
    container_name: webgocalc_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webgocalc_app
    ports:
      - "8080:8080"
    environment:
      ENV: ${ENV}
      STORAGE_HOST: ${DB_HOST}
      STORAGE_PORT: ${DB_PORT}
      STORAGE_USER: ${DB_USER}
      STORAGE_PASSWORD: ${DB_PASSWORD}
      STORAGE_DBNAME: ${DB_NAME}
      HTTP_SERVER_ADDRESS: ${HTTP_SERVER_ADDRESS}
      HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
      HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
    - ./migrations:/migrations
    
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge