
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webgocalc_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_db
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: webgocalc_postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  
networks:
  app-network:
    driver: bridge