// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Student struct {
	ID        int64
	Name      string
	SClass    string
	School    string
	OrderDay  int16
	OrderTime pgtype.Time
	OrderCost int16
}

type StudentEvent struct {
	ID         int64
	StudentID  int64
	EventDate  pgtype.Date
	OrderTime  pgtype.Time
	OrderCost  int16
	OrderCheck pgtype.Bool
}
