env: "local" #local, dev, prod
storage: 
    path: "./storage/storage.db"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "...."
    dbname: "storage"
http_server:
  address: "localhost:8082"
  timeout: 5s #read timeout
  idle_timeout: 60s #connect timeout
