basePath: /api
consumes:
- application/json
definitions:
  nocsqlcpg.CreateStudentSwagger:
    properties:
      name:
        type: string
      orderCost:
        type: integer
      orderDay:
        type: integer
      orderTime:
        $ref: '#/definitions/nocsqlcpg.OrderTime'
      school:
        type: string
      sclass:
        type: string
    type: object
  nocsqlcpg.EventDate:
    properties:
      infinityModifier:
        type: integer
      time:
        type: string
      valid:
        type: boolean
    type: object
  nocsqlcpg.OrderCheck:
    properties:
      bool:
        type: boolean
      valid:
        type: boolean
    type: object
  nocsqlcpg.OrderTime:
    properties:
      microseconds:
        type: integer
      valid:
        type: boolean
    type: object
  nocsqlcpg.StudentEventSwagger:
    properties:
      eventDate:
        $ref: '#/definitions/nocsqlcpg.EventDate'
      id:
        type: integer
      orderCheck:
        $ref: '#/definitions/nocsqlcpg.OrderCheck'
      orderCost:
        type: integer
      orderTime:
        $ref: '#/definitions/nocsqlcpg.OrderTime'
      studentID:
        type: integer
    type: object
  nocsqlcpg.StudentSwagger:
    properties:
      id:
        type: integer
      name:
        type: string
      orderCost:
        type: integer
      orderDay:
        type: integer
      orderTime:
        $ref: '#/definitions/nocsqlcpg.OrderTime'
      school:
        type: string
      sclass:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: lyoshabura@gmail.com
    name: API Support
    url: http://http://81.177.220.96/
  description: API для управления студентами и событиями в календаре.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Student and Calendar API
  version: "1.0"
paths:
  /api/calendar:
    get:
      consumes:
      - application/json
      description: Возвращает события календаря на указанный день.
      parameters:
      - description: Дата в формате YYYY-MM-DD
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/nocsqlcpg.StudentEventSwagger'
            type: array
        "400":
          description: неверные данные
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Получить список событий
      tags:
      - calendar
  /api/students:
    get:
      description: Получить все записи студентов
      produces:
      - application/json
      responses:
        "200":
          description: Список студентов
          schema:
            items:
              $ref: '#/definitions/nocsqlcpg.StudentSwagger'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Получить список студентов
    post:
      consumes:
      - application/json
      description: Добавляет нового студента в базу данных.
      parameters:
      - description: Данные студента
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/nocsqlcpg.CreateStudentSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/nocsqlcpg.StudentSwagger'
        "400":
          description: неверные данные
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Создать студента
      tags:
      - students
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
